name: Gaoson's Barber Shop
shortName: Gaoson
tagline: Crafted Cuts. Sharp Style.
description: Salon de coiffure homme premium ancré au cœur de Biot. Coupe nette,
  barbe sculptée, rasage à la lame
address:
  street: 32 Rue Saint-Sébastien
  postalCode: "06410"
  city: Biot
  country: France
hours:
  - days: Mardi — Samedi
    time: 08:45 — 19:00
  - days: Lundi
    time: Fermé
links:
  booksy: https://booksy.com/fr-fr/20935_gaosons-barber-shop_barbier_118662_biot#ba_s=seo
  instagram: https://www.instagram.com/gaosonbarbershop/
  googleMaps: https://www.google.com/maps/search/?api=1&query=32+Rue+Saint-S%C3%A9bastien+06410+Biot
legal:
  siret: 350 067 146 00018
  hostName: IONOS Se
  hostAddress: 7 place de la Gare, BP 70109, 57201 Sarreguemines
elfsightWidgetId: dbe5b599-f9b6-4952-a657-b26fe8c232c5
